version: "3.1"

services:
  gambi-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - ./public/uploads:/home/node/app/public/uploads
    environment:
      - PORT=4000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'
