version: "3.1"

services:
  gambi-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=4000
